---
- name: "Enable epel repository"
  yum:
    name: "epel-release"
    state: "latest"

- name: "Install packages required by role (RedHat)"
  yum:
    name: "{{ item }}"
    state: "latest"
  with_items: 
    - "git"

- name: "Install required packages (RedHat)"
  yum:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "clamav"
    - "clamav-data"
    - "clamav-devel"
    - "clamav-filesystem"
    - "clamav-lib"
    - "clamav-server"
    - "clamav-scanner"
    - "clamav-update"
    - "clamav-scanner-systemd"
    - "clamav-server-systemd"

- name: "Config /etc/freshclam.conf from template"
  template:
    src: "etc/freshclam.conf.j2"
    dest: "/etc/freshclam.conf"
    backup: "yes"

- name: "Config /etc/sysconfig/freshclam from template"
  template:
    src: "etc/sysconfig/freshclam.j2"
    dest: "/etc/sysconfig/freshclam"
    backup: "yes"

- name: "Include download-sigs.yml"
  include: "download-sigs.yml"

- name: "Config /etc/clamd.d/scan.conf from template"
  template: 
    src: "etc/clamd.d/scan.conf.j2"
    dest: "/etc/clamd.d/scan.conf"
    backup: "yes"

- name: "Symlink /etc/clamd.d/scan.conf to /etc/clamd.conf"
  file:
    src: "/etc/clamd.d/scan.conf"
    dest: "/etc/clamd.conf"
    state: "link"

- name: "Enable and start services"
  service:
    name: "clamd@scan"
    state: "started"
    enabled: "yes"

