---

- name: "Install packages required by role (Ubuntu14)"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items: 
    - "git"

- name: "Install clamav packages (Ubuntu14)"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items: 
    - "clamav"
    - "clamav-daemon"

# If CLAMAV_SOCKET_TYPE is not defined, use file option
- set_fact:
    CLAMAV_SOCKET_TYPE: "file"
  when:  CLAMAV_SOCKET_TYPE is not defined

- name: "Configure clamav socket (tcp 1/3)"
  lineinfile:
     path: "/etc/clamav/clamd.conf"
     regexp: "^LocalSocket\ /var/run/clamav/clamd.ctl"
     line: "#LocalSocket\ /var/run/clamav/clamd.ctl"
  when: CLAMAV_SOCKET_TYPE ==  'tcp'

- name: "Configure clamav socket (file 1/3)"
  lineinfile:
     path: "/etc/clamav/clamd.conf"
     regexp: "^#LocalSocket\ /var/run/clamav/clamd.ctl"
     line: "LocalSocket\ /var/run/clamav/clamd.ctl"
  when: CLAMAV_SOCKET_TYPE !=  'tcp'

- name: "Configure clamav socket (tcp 2/3)"
  lineinfile:
     path: "/etc/clamav/clamd.conf"
     regexp: "^TCPSocket\ "
     line: "TCPSocket\ {{ CLAMAV_TCP_PORT }}"
     state: present
  when: CLAMAV_SOCKET_TYPE ==  'tcp'

- name: "Configure clamav socket (file 2/3)"
  lineinfile:
     path: "/etc/clamav/clamd.conf"
     regexp: "^TCPSocket\ "
     state: absent
  when: CLAMAV_SOCKET_TYPE !=  'tcp'

- name: "Configure clamav socket (tcp 3/3)"
  lineinfile:
     path: "/etc/clamav/clamd.conf"
     regexp: "^TCPAddr\ "
     line: "TCPAddr\ {{ CLAMAV_TCP_ADDR }}"
     state: present
  when: CLAMAV_SOCKET_TYPE ==  'tcp'

- name: "Configure clamav socket (file 3/3)"
  lineinfile:
     path: "/etc/clamav/clamd.conf"
     regexp: "^TCPAddr\ "
     state: absent
  when: CLAMAV_SOCKET_TYPE !=  'tcp'

- name: "Configure clamav MaxFileSize"
  lineinfile:
     path: "/etc/clamav/clamd.conf"
     regexp: "^MaxFileSize "
     line: "MaxFileSize {{ CLAMAV_MAX_FILE_SIZE }}"

- name: "Configure clamav StreamMaxLength"
  lineinfile:
     path: "/etc/clamav/clamd.conf"
     regexp: "^StreamMaxLength "
     line: "StreamMaxLength {{ CLAMAV_MAX_STREAM_LENGTH }}"

- name: "Configure clamav MaxScanSize"
  lineinfile:
     path: "/etc/clamav/clamd.conf"
     regexp: "^MaxScanSize "
     line: "MaxScanSize {{ CLAMAV_MAX_SCAN_SIZE }}"

- name: "Include download-sigs.yml"
  include: "download-sigs.yml"

- name: "Enable services"
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: "yes"
  with_items:
    - "clamav-daemon"
