---

- name: "Install packages required by role (Ubuntu)"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items: 
    - "git"

- name: "Install clamav packages (Ubuntu)"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items: 
    - "clamav"
    - "clamav-daemon"

- name: "Configure clamav MaxFileSize"
  lineinfile:
     path: "/etc/clamav/clamd.conf"
     regexp: "^MaxFileSize "
     line: "MaxFileSize {{ CLAMAV_MAX_FILE_SIZE }}"

- name: "Configure clamav StreamMaxLength"
  lineinfile:
     path: "/etc/clamav/clamd.conf"
     regexp: "^StreamMaxLength "
     line: "StreamMaxLength {{ CLAMAV_MAX_STREAM_LENGTH }}"

- name: "Configure clamav MaxScanSize"
  lineinfile:
     path: "/etc/clamav/clamd.conf"
     regexp: "^MaxScanSize "
     line: "MaxScanSize {{ CLAMAV_MAX_SCAN_SIZE }}"

- name: "Include download-sigs.yml"
  include: "download-sigs.yml"

- name: "Enable services"
  service:
    name: "{{ item }}"
    state: "started"
    enabled: "yes"
  with_items:
    - "clamav-daemon"



